# Generated by Django 4.1.5 on 2023-02-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='newspaper_name',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
