# Generated by Django 4.1.5 on 2023-03-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_newspaper_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='newsimage/'),
        ),
    ]
